apiVersion: v1
kind: Service
metadata:
  name: cilist-backend
  labels:
    app: cilist
    tier: backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: backend-port
  selector:
    app: cilist
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilist-backend
  namespace: production
spec:
  selector:
    matchLabels:
      app: cilist
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: cilist
        tier: backend
    spec:
      containers:
      - name: cilist-backend
        image: 128532453810.dkr.ecr.ap-southeast-1.amazonaws.com/cilist-backend:IMAGE_TAG
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 80Mi
            cpu: 50m
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: cilist-backend
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cilist-backend
              key: password
        - name: DB_DATABASE
          value: peopleproduction
        - name: DB_HOST
          value: http://rdshost
